language: scala
scala:
  - 2.11.4
jdk:
  - oraclejdk7
before_script:
  - rm project/sbt-idea.sbt
  - rm project/sbt-pgp.sbt
  - rm project/sbt-updates.sbt
script:
  - ./scalikejdbc-cli/scripts/setup.sh
  - source ~/.bash_profile
  - scalikejdbc-cli
