language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

addons:
  postgresql: "9.4"

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_script:
  - rm project/sbt-idea.sbt
  - rm project/sbt-pgp.sbt
  - rm project/sbt-updates.sbt
  - psql -c "CREATE ROLE sa WITH SUPERUSER LOGIN PASSWORD 'sa';" -U postgres
  - psql -c "CREATE DATABASE scalikejdbc;" -U postgres
  - mysql -e 'GRANT ALL ON *.* TO sa@"localhost"IDENTIFIED BY "sa";FLUSH PRIVILEGES;' -uroot
  - mysql -e "CREATE DATABASE scalikejdbc;" -usa -psa

script:
  - export TZ=${TIMEZONE}
  - bash -x ./travis_before.sh
  - git add . --all
  - travis_retry ./travis.sh
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf

env:
  matrix:
    - SCALIKEJDBC_DATABASE="mysql"        TIMEZONE="America/New_York"
    - SCALIKEJDBC_DATABASE="postgresql"   TIMEZONE="America/New_York"
    - SCALIKEJDBC_DATABASE="mysql"        TIMEZONE="Japan"
    - SCALIKEJDBC_DATABASE="postgresql"   TIMEZONE="Japan"
    - SCALIKEJDBC_DATABASE="mysql"        TIMEZONE="GMT"
    - SCALIKEJDBC_DATABASE="postgresql"   TIMEZONE="GMT"
    - SCALIKEJDBC_DATABASE="mysql"        TIMEZONE="Pacific/Honolulu"
    - SCALIKEJDBC_DATABASE="postgresql"   TIMEZONE="Pacific/Honolulu"
