version: 1.0.{build}
clone_depth: 3
services: mssql2014
build_script:
- sqlcmd -S ".\SQL2014" -U sa -P Password12! -Q "create database scalikejdbc;"
- del project\sbt-idea.sbt
- del project\sbt-pgp.sbt
- del project\sbt-updates.sbt
- del scalikejdbc-core\src\test\resources\jdbc.properties
- move scalikejdbc-core\src\test\resources\jdbc_sqlserver.properties scalikejdbc-core\src\test\resources\jdbc.properties
- sbt core/test
#- sbt test:compile "project root211" testSequential
